const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const bookCtrl = require('../controllers/bookController');
router.post('/', auth, bookCtrl.createBook);
router.get('/', bookCtrl.listBooks);
router.get('/:id', bookCtrl.getBook);
router.put('/:id', auth, bookCtrl.updateBook);
router.delete('/:id', auth, bookCtrl.deleteBook);
module.exports = router;
